In [1]:
import mindspore as ms
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

In [2]:
array = np.asarray([[1,2],[3,4]])

In [3]:
x = ms.Tensor(array, ms.dtype.int32)

In [4]:
print(x)

[[1 2]
 [3 4]]


In [6]:
tensor = ms.Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
print("First row: {}".format(tensor[0]))
print("First column: {}".format(tensor[:, 0]))
print("Last column: {}".format(tensor[..., -1]))

First row: [0. 1.]
First column: [0. 2.]
Last column: [1. 3.]


In [9]:
data1 = ms.Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = ms.Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
op = ms.ops.Stack()
output = op([data1, data2])
print(output)
print(data1.shape, output.shape)


[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
(2, 2) (2, 2, 2)


In [8]:
output.shape

(2, 2, 2)